name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false  # never use caching in release builds

      - uses: pnpm/action-setup@v6
        with:
          version: 11

      - run: pnpm ci
      - run: pnpm run build --if-present
      - run: pnpm test
      - run: pnpm publish  # Or: npm stage publish